### PR TITLE
APICLIENT-7: Fix timezones

### PR DESCRIPTION
**Pull request by maxammann**

### CODE REVIEW

**Review by NKlug — APPROVED** [review]
Why do you sometimes use 'Europe/Berlin' and sometimes 'GMT'?

**Comment by maxammann** [comment]
@NKlug yes that is the undocumented specification from the cms :)

**Review by michael-markl — APPROVED** [review]
btw. have you tried to use https://www.npmjs.com/package/timezone-mock as an alternative fix for the development problem?

**Comment by maxammann** [comment]
@Schedulaar I first tried to fix it that way. By just adding one line to the setupTests.js

But then I realised that this would be just a workaround. And that we actually have problems with our timezones. As soon as we fixed these we won't have any issues with testing.

The problem is not just the tests which lack a specific timezone but also our implementations which parse everything in local time. (Including the gmt_modified timestamp which is obviously wrong)

**Review by steffenkleinle — APPROVED** [review]

**Comment by maxammann** [comment]
@Schedulaar @NKlug @klinzo please review this again as the API for events changed.

**Comment by maxammann** [comment]
https://github.com/Integreat/cms/pull/932

This change is already live!

**Review by michael-markl — APPROVED** [review]

**Review by steffenkleinle — APPROVED** [review]

**Pull request merged**
